version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app_dev

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - app_dev

networks:
  app_dev:
    driver: bridge
